// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/faq"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// FAQUpdate is the builder for updating FAQ entities.
type FAQUpdate struct {
	config
	hooks    []Hook
	mutation *FAQMutation
}

// Where appends a list predicates to the FAQUpdate builder.
func (_u *FAQUpdate) Where(ps ...predicate.FAQ) *FAQUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *FAQUpdate) SetTitle(v string) *FAQUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *FAQUpdate) SetNillableTitle(v *string) *FAQUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAnswer sets the "answer" field.
func (_u *FAQUpdate) SetAnswer(v string) *FAQUpdate {
	_u.mutation.SetAnswer(v)
	return _u
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_u *FAQUpdate) SetNillableAnswer(v *string) *FAQUpdate {
	if v != nil {
		_u.SetAnswer(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *FAQUpdate) SetEnabled(v bool) *FAQUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *FAQUpdate) SetNillableEnabled(v *bool) *FAQUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *FAQUpdate) SetSortOrder(v int) *FAQUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *FAQUpdate) SetNillableSortOrder(v *int) *FAQUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *FAQUpdate) AddSortOrder(v int) *FAQUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FAQUpdate) SetUpdatedAt(v time.Time) *FAQUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FAQMutation object of the builder.
func (_u *FAQUpdate) Mutation() *FAQMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FAQUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FAQUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FAQUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FAQUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FAQUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := faq.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FAQUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := faq.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "FAQ.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Answer(); ok {
		if err := faq.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`ent: validator failed for field "FAQ.answer": %w`, err)}
		}
	}
	return nil
}

func (_u *FAQUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(faq.Table, faq.Columns, sqlgraph.NewFieldSpec(faq.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(faq.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Answer(); ok {
		_spec.SetField(faq.FieldAnswer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(faq.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(faq.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(faq.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(faq.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{faq.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FAQUpdateOne is the builder for updating a single FAQ entity.
type FAQUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FAQMutation
}

// SetTitle sets the "title" field.
func (_u *FAQUpdateOne) SetTitle(v string) *FAQUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *FAQUpdateOne) SetNillableTitle(v *string) *FAQUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAnswer sets the "answer" field.
func (_u *FAQUpdateOne) SetAnswer(v string) *FAQUpdateOne {
	_u.mutation.SetAnswer(v)
	return _u
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_u *FAQUpdateOne) SetNillableAnswer(v *string) *FAQUpdateOne {
	if v != nil {
		_u.SetAnswer(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *FAQUpdateOne) SetEnabled(v bool) *FAQUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *FAQUpdateOne) SetNillableEnabled(v *bool) *FAQUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *FAQUpdateOne) SetSortOrder(v int) *FAQUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *FAQUpdateOne) SetNillableSortOrder(v *int) *FAQUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *FAQUpdateOne) AddSortOrder(v int) *FAQUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FAQUpdateOne) SetUpdatedAt(v time.Time) *FAQUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FAQMutation object of the builder.
func (_u *FAQUpdateOne) Mutation() *FAQMutation {
	return _u.mutation
}

// Where appends a list predicates to the FAQUpdate builder.
func (_u *FAQUpdateOne) Where(ps ...predicate.FAQ) *FAQUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FAQUpdateOne) Select(field string, fields ...string) *FAQUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FAQ entity.
func (_u *FAQUpdateOne) Save(ctx context.Context) (*FAQ, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FAQUpdateOne) SaveX(ctx context.Context) *FAQ {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FAQUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FAQUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FAQUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := faq.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FAQUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := faq.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "FAQ.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Answer(); ok {
		if err := faq.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`ent: validator failed for field "FAQ.answer": %w`, err)}
		}
	}
	return nil
}

func (_u *FAQUpdateOne) sqlSave(ctx context.Context) (_node *FAQ, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(faq.Table, faq.Columns, sqlgraph.NewFieldSpec(faq.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FAQ.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, faq.FieldID)
		for _, f := range fields {
			if !faq.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != faq.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(faq.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Answer(); ok {
		_spec.SetField(faq.FieldAnswer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(faq.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(faq.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(faq.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(faq.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &FAQ{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{faq.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
