// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/faq"
)

// FAQCreate is the builder for creating a FAQ entity.
type FAQCreate struct {
	config
	mutation *FAQMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (_c *FAQCreate) SetTitle(v string) *FAQCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetAnswer sets the "answer" field.
func (_c *FAQCreate) SetAnswer(v string) *FAQCreate {
	_c.mutation.SetAnswer(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *FAQCreate) SetEnabled(v bool) *FAQCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *FAQCreate) SetNillableEnabled(v *bool) *FAQCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *FAQCreate) SetSortOrder(v int) *FAQCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *FAQCreate) SetNillableSortOrder(v *int) *FAQCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FAQCreate) SetCreatedAt(v time.Time) *FAQCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FAQCreate) SetNillableCreatedAt(v *time.Time) *FAQCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FAQCreate) SetUpdatedAt(v time.Time) *FAQCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FAQCreate) SetNillableUpdatedAt(v *time.Time) *FAQCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the FAQMutation object of the builder.
func (_c *FAQCreate) Mutation() *FAQMutation {
	return _c.mutation
}

// Save creates the FAQ in the database.
func (_c *FAQCreate) Save(ctx context.Context) (*FAQ, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FAQCreate) SaveX(ctx context.Context) *FAQ {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FAQCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FAQCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FAQCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := faq.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := faq.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := faq.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := faq.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FAQCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "FAQ.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := faq.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "FAQ.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Answer(); !ok {
		return &ValidationError{Name: "answer", err: errors.New(`ent: missing required field "FAQ.answer"`)}
	}
	if v, ok := _c.mutation.Answer(); ok {
		if err := faq.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`ent: validator failed for field "FAQ.answer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "FAQ.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "FAQ.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FAQ.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FAQ.updated_at"`)}
	}
	return nil
}

func (_c *FAQCreate) sqlSave(ctx context.Context) (*FAQ, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FAQCreate) createSpec() (*FAQ, *sqlgraph.CreateSpec) {
	var (
		_node = &FAQ{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(faq.Table, sqlgraph.NewFieldSpec(faq.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(faq.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Answer(); ok {
		_spec.SetField(faq.FieldAnswer, field.TypeString, value)
		_node.Answer = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(faq.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(faq.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(faq.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(faq.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FAQ.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FAQUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *FAQCreate) OnConflict(opts ...sql.ConflictOption) *FAQUpsertOne {
	_c.conflict = opts
	return &FAQUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FAQ.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FAQCreate) OnConflictColumns(columns ...string) *FAQUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FAQUpsertOne{
		create: _c,
	}
}

type (
	// FAQUpsertOne is the builder for "upsert"-ing
	//  one FAQ node.
	FAQUpsertOne struct {
		create *FAQCreate
	}

	// FAQUpsert is the "OnConflict" setter.
	FAQUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *FAQUpsert) SetTitle(v string) *FAQUpsert {
	u.Set(faq.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *FAQUpsert) UpdateTitle() *FAQUpsert {
	u.SetExcluded(faq.FieldTitle)
	return u
}

// SetAnswer sets the "answer" field.
func (u *FAQUpsert) SetAnswer(v string) *FAQUpsert {
	u.Set(faq.FieldAnswer, v)
	return u
}

// UpdateAnswer sets the "answer" field to the value that was provided on create.
func (u *FAQUpsert) UpdateAnswer() *FAQUpsert {
	u.SetExcluded(faq.FieldAnswer)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *FAQUpsert) SetEnabled(v bool) *FAQUpsert {
	u.Set(faq.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *FAQUpsert) UpdateEnabled() *FAQUpsert {
	u.SetExcluded(faq.FieldEnabled)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *FAQUpsert) SetSortOrder(v int) *FAQUpsert {
	u.Set(faq.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *FAQUpsert) UpdateSortOrder() *FAQUpsert {
	u.SetExcluded(faq.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *FAQUpsert) AddSortOrder(v int) *FAQUpsert {
	u.Add(faq.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FAQUpsert) SetUpdatedAt(v time.Time) *FAQUpsert {
	u.Set(faq.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FAQUpsert) UpdateUpdatedAt() *FAQUpsert {
	u.SetExcluded(faq.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FAQ.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FAQUpsertOne) UpdateNewValues() *FAQUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(faq.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FAQ.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FAQUpsertOne) Ignore() *FAQUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FAQUpsertOne) DoNothing() *FAQUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FAQCreate.OnConflict
// documentation for more info.
func (u *FAQUpsertOne) Update(set func(*FAQUpsert)) *FAQUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FAQUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *FAQUpsertOne) SetTitle(v string) *FAQUpsertOne {
	return u.Update(func(s *FAQUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *FAQUpsertOne) UpdateTitle() *FAQUpsertOne {
	return u.Update(func(s *FAQUpsert) {
		s.UpdateTitle()
	})
}

// SetAnswer sets the "answer" field.
func (u *FAQUpsertOne) SetAnswer(v string) *FAQUpsertOne {
	return u.Update(func(s *FAQUpsert) {
		s.SetAnswer(v)
	})
}

// UpdateAnswer sets the "answer" field to the value that was provided on create.
func (u *FAQUpsertOne) UpdateAnswer() *FAQUpsertOne {
	return u.Update(func(s *FAQUpsert) {
		s.UpdateAnswer()
	})
}

// SetEnabled sets the "enabled" field.
func (u *FAQUpsertOne) SetEnabled(v bool) *FAQUpsertOne {
	return u.Update(func(s *FAQUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *FAQUpsertOne) UpdateEnabled() *FAQUpsertOne {
	return u.Update(func(s *FAQUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *FAQUpsertOne) SetSortOrder(v int) *FAQUpsertOne {
	return u.Update(func(s *FAQUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *FAQUpsertOne) AddSortOrder(v int) *FAQUpsertOne {
	return u.Update(func(s *FAQUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *FAQUpsertOne) UpdateSortOrder() *FAQUpsertOne {
	return u.Update(func(s *FAQUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FAQUpsertOne) SetUpdatedAt(v time.Time) *FAQUpsertOne {
	return u.Update(func(s *FAQUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FAQUpsertOne) UpdateUpdatedAt() *FAQUpsertOne {
	return u.Update(func(s *FAQUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *FAQUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FAQCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FAQUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FAQUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FAQUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FAQCreateBulk is the builder for creating many FAQ entities in bulk.
type FAQCreateBulk struct {
	config
	err      error
	builders []*FAQCreate
	conflict []sql.ConflictOption
}

// Save creates the FAQ entities in the database.
func (_c *FAQCreateBulk) Save(ctx context.Context) ([]*FAQ, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FAQ, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FAQMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FAQCreateBulk) SaveX(ctx context.Context) []*FAQ {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FAQCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FAQCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FAQ.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FAQUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *FAQCreateBulk) OnConflict(opts ...sql.ConflictOption) *FAQUpsertBulk {
	_c.conflict = opts
	return &FAQUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FAQ.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FAQCreateBulk) OnConflictColumns(columns ...string) *FAQUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FAQUpsertBulk{
		create: _c,
	}
}

// FAQUpsertBulk is the builder for "upsert"-ing
// a bulk of FAQ nodes.
type FAQUpsertBulk struct {
	create *FAQCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FAQ.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FAQUpsertBulk) UpdateNewValues() *FAQUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(faq.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FAQ.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FAQUpsertBulk) Ignore() *FAQUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FAQUpsertBulk) DoNothing() *FAQUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FAQCreateBulk.OnConflict
// documentation for more info.
func (u *FAQUpsertBulk) Update(set func(*FAQUpsert)) *FAQUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FAQUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *FAQUpsertBulk) SetTitle(v string) *FAQUpsertBulk {
	return u.Update(func(s *FAQUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *FAQUpsertBulk) UpdateTitle() *FAQUpsertBulk {
	return u.Update(func(s *FAQUpsert) {
		s.UpdateTitle()
	})
}

// SetAnswer sets the "answer" field.
func (u *FAQUpsertBulk) SetAnswer(v string) *FAQUpsertBulk {
	return u.Update(func(s *FAQUpsert) {
		s.SetAnswer(v)
	})
}

// UpdateAnswer sets the "answer" field to the value that was provided on create.
func (u *FAQUpsertBulk) UpdateAnswer() *FAQUpsertBulk {
	return u.Update(func(s *FAQUpsert) {
		s.UpdateAnswer()
	})
}

// SetEnabled sets the "enabled" field.
func (u *FAQUpsertBulk) SetEnabled(v bool) *FAQUpsertBulk {
	return u.Update(func(s *FAQUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *FAQUpsertBulk) UpdateEnabled() *FAQUpsertBulk {
	return u.Update(func(s *FAQUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *FAQUpsertBulk) SetSortOrder(v int) *FAQUpsertBulk {
	return u.Update(func(s *FAQUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *FAQUpsertBulk) AddSortOrder(v int) *FAQUpsertBulk {
	return u.Update(func(s *FAQUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *FAQUpsertBulk) UpdateSortOrder() *FAQUpsertBulk {
	return u.Update(func(s *FAQUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FAQUpsertBulk) SetUpdatedAt(v time.Time) *FAQUpsertBulk {
	return u.Update(func(s *FAQUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FAQUpsertBulk) UpdateUpdatedAt() *FAQUpsertBulk {
	return u.Update(func(s *FAQUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *FAQUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FAQCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FAQCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FAQUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
